name: Publish Package to NPM

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment:
      name: production
      url: https://www.npmjs.com/package/aws-kms-signer-nodejs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm ci

      - name: Setup test environment
        run: |
          echo "KMS_KEY_ID=${{ secrets.KMS_KEY_ID }}" >> $GITHUB_ENV
          echo "ETHEREUM_RPC_URL=https://ethereum-sepolia-rpc.publicnode.com" >> $GITHUB_ENV
          echo "TRON_RPC_URL=https://api.nileex.io/" >> $GITHUB_ENV

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
